import nltk

TOKEN_FILE_PATH='token.txt'

# chain_length is the length of the keys which we use in the word_bank table - higher = more structured, more similar to input text
# as chain_length goes to infinity, tobor just spits out the original text it got
CHAIN_LENGTH = 3
MAX_CHAIN_LENGTH = 6

# number of sentences tobor will have in a story of corresponding length
SHORT_STORY_SENT_COUNT = 4
MED_STORY_SENT_COUNT = 12
LONG_STORY_SENT_COUNT = 24

# this is how many words in the future tobor will look at when deciding what the next word will be
# this is critical to building better sentences - higher numbers means more planning in the word choice
# this is exponential growth at its worst - even numbers like 4 or 5 would increase computational time by an order of magnitude
SEARCH_DEPTH = 3

# this uses the frequency of a word in the corpus to weight how good it is - more frequent words will be valued higher
FREQUENCY_SCORE_MOD = 0.25
DUPLICATE_SCORE_MOD = 0.5
MAX_SENTENCE_LENGTH = 100

# a mapping between verbs and their root meaning - e.g. 'stagger' gets mapped to 'move'
# only contains verbs which should significantly change the state of the story
VERB_ROOT_MAP = {
    "trade" : "give",
    "bring" : "give",
    "weld" : "emplace",
    "place" : "give",
    "borrow" : "take",
    "steal" : "take",
    "trundle" : "move",
    "offer" : "give",
    "recollect" : "take",
    "pin" : "emplace",
    "buy" : "take",
    "round" : "move",
    "bar": "emplace",
    "arrest" : "emplace",
    "approach" : "move",
    "strode" : "move",
    "go" : "move",
    "pour" : "give",
    "enter" : "move",
    "bob" : "move",
    "accept" : "take",
    "continue" : "move",
    "gain" : "take",
    "possess" : "take",
    "wriggle" : "move",
    "dance" : "move",
    "proceed" : "move",
    "dip" : "move",
    "trail" : "move",
    "visit" : "move",
    "tilt" : "move",
    "remain" : "emplace",
    "lodge" : "emplace",
    "bend" : "move",
    "ride" : "move",
    "fling" : "move",
    "dash" : "move",
    "balance" : "emplace",
    "unfasten" : "release",
    "grant" : "give",
    "open" : "open",
    "drag" : "move",
    "come" : "move",
    "abandon" : "move",
    "tumble" : "move",
    "sling" : "move",
    "hop" : "move",
    "crack" : "destroy",
    "jump" : "move",
    "creep" : "move",
    "lose" : "give",
    "free" : "free",
    "float" : "move",
    "eat" : "destroy",
    "purchase" : "take",
    "tear" : "destroy",
    "speed" : "move",
    "flow" : "move",
    "dive" : "move",
    "stop" : "emplace",
    "tread" : "move",
    "pull" : "move",
    "put" : "emplace",
    "bind" : "emplace",
    "roll" : "move",
    "give" : "give",
    "seize" : "take",
    "scamper" : "move",
    "walk" : "move",
    "drift" : "move",
    "charge" : "move",
    "tackle" : "move",
    "prevent" : "emplace",
    "halt" : "emplace",
    "bolt" : "move",
    "slip" : "move",
    "shed" : "give",
    "turn" : "move",
    "leave" : "move",
    "emerge" : "move",
    "take" : "take",
    "run" : "move",
    "journey" : "move",
    "step" : "move",
    "leapt" : "move",
    "leap" : "move",
    "provide" : "give",
    "liberate" : "free",
    "eaten" : "destroy",
    "plant" : "emplace",
    "bounce" : "move",
    "untie" : "free",
    "push" : "move",
    "squat" : "move",
    "fasten" : "emplace",
    "stick" : "emplace",
    "get" : "take",
    "sell" : "give",
    "trot" : "move",
    "escape" : "free",
    "stoop" : "move",
    "slide" : "move",
    "vacate" : "move",
    "stride" : "move",
    "chase" : "move",
    "fly" : "move",
    "collect" : "take",
    "march" : "move",
    "kill" : "destroy",
    "capture" : "emplace",
    "carry" : "take",
    "flee" : "move",
    "rescue" : "free",
    "die" : "destroy",
    "release" : "free",
    "dump" : "give",
    "destroy" : "destroy",
    "strut" : "move",
    "stroll" : "move",
    "soar" : "move",
    "limp" : "move",
    "crawl" : "move",
    "kidnap" : "take",
    "follow" : "move",
    "kneel" : "move",
    "emplace" : "emplace",
    "embed" : "emplace",
    "bury" : "emplace",
    "throw" : "move",
    "drive" : "move",
    "fetter" : "emplace",
    "break" : "destroy",
    "flutter" : "move",
    "swim" : "move",
    "hasten" : "move",
    "trudge" : "move",
    "scramble" : "move",
    "duck" : "move",
    "gallop" : "move"
}